#include <linea.h>
#include "drawlib.h"

void plot_line(unsigned short x1, unsigned short y1,
               unsigned short x2, unsigned short y2,
               short style, short mode)
{
	/* do line-a call to plot a line */

	X1 = x1;
	Y1 = y1;
	X2 = x2;
	Y2 = y2;
	LNMASK = style;
	WMODE = mode;
	LSTLIN = 0;
	linea3();
}

/* there might be a prettier way to do this idk */
void draw_play_area()
{
	/* left border */
	plot_line(PLAY_AREA_OFFSET_X - 8, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X - 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED, XOR);
	
        plot_line(PLAY_AREA_OFFSET_X - 6, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X - 6, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED2, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X - 5, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X - 5, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED, XOR);

	plot_line(PLAY_AREA_OFFSET_X - 4, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X - 4, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED2, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X - 3, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X - 3, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED, XOR);

	plot_line(PLAY_AREA_OFFSET_X - 2, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X - 2, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	SOLID, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X - 1, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X - 1, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	SOLID, XOR);
	
	/* right border */
	plot_line(PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 1, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 1, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	SOLID, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 2, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 2, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	SOLID, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 3, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 3, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 4, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 4, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED2, XOR);

	plot_line(PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 5, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 5, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 6, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 6, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED2, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 8, PLAY_AREA_OFFSET_Y,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	DASHED, XOR);

	/* bottom border */
	plot_line(PLAY_AREA_OFFSET_X - 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 1,
	SOLID, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X - 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 2,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 2,
	SOLID, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X - 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 3,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 3,
	DASHED, XOR);
	
	plot_line(PLAY_AREA_OFFSET_X - 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 4,
	PLAY_AREA_OFFSET_X + PLAY_AREA_WIDTH_PIXELS + 8, PLAY_AREA_OFFSET_Y + PLAY_AREA_HEIGHT_PIXELS + 4,
	DASHED2, XOR);
}
