#ifndef FONTLIB_H
#define FONTLIB_H

#include "typedef.h"

void num_0(UWORD *base, int x, int y);
void num_1(UWORD *base, int x, int y);
void num_2(UWORD *base, int x, int y);
void num_3(UWORD *base, int x, int y);
void num_4(UWORD *base, int x, int y);
void num_5(UWORD *base, int x, int y);
void num_6(UWORD *base, int x, int y);
void num_7(UWORD *base, int x, int y);
void num_8(UWORD *base, int x, int y);
void num_9(UWORD *base, int x, int y);
void write_c(UWORD *base, int x, int y);
void write_e(UWORD *base, int x, int y);
void write_i(UWORD *base, int x, int y);
void write_l(UWORD *base, int x, int y);
void write_n(UWORD *base, int x, int y);
void write_o(UWORD *base, int x, int y);
void write_r(UWORD *base, int x, int y);
void write_s(UWORD *base, int x, int y);
void write_t(UWORD *base, int x, int y);
void write_x(UWORD *base, int x, int y);
void write_colon(UWORD *base, int x, int y);
#endif