/* INPUT.H
*
*   Colton Paquette		cpaqu904@mtroyal.ca
*   COMP 2659           Term Project
*   Winter 2020         Tyson Kendon
*
*   Public Functions:   int is_pressed();
*              			-   Checks to see if a key is pressed.
*
*                       int read_key();
*                       -   Reads the pressed key.
*
*/
#ifndef INPUT_H
#define INPUT_H

int is_pressed();
int read_key();

#endif